config/routes.rb
Rails.application.routes.draw do

  root 'bikes#index'
  resources :bikes

  resources :motorcycles

end

app/models/bike.rb
class Bike
  include Mongoid::Document
  field :name 
  field :brand 
  field :speed, type: Float
end

app/models/motorcycle.rb
class Motorcycle
  include Mongoid::Document
  field :name
  field :brand
  field :speed, type: Float
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
	
	def index
		@bikes = Bike.all
	end

	def show
		@bike = Bike.find(params[:id])
	end

	def new
		@bike = Bike.new
	end

	def create
		@bike = Bike.new (bike_params)

		if @bike.save
			redirect_to bikes_path
		else
			render :new
		end
	end

	def edit
		@bike = Bike.find(params[:id])
	end

	def update

		@bike = Bike.find(params[:id])

		if @bike.update_attributes(bike_params)
			redirect_to bikes_path
		else 
			render "edit"
		end
	end
	
	def destroy
		@bike = Bike.find(params[:id])
		@bike.destroy
		redirect_to bikes_path
	end

	

	private

	def bike_params
		params.require(:bike).permit(:name, :brand, :speed)
	end
end

app/controllers/motorcycles_controller.rb
class MotorcyclesController < ApplicationController
	
	def index
		@motorcycles = Motorcycle.all
	end

	def show
		@motorcycle = Motorcycle.find(params[:id])
	end

	def new
		@motorcycle = Motorcycle.new
	end

	def create
		@motorcycle = Motorcycle.new (motorcycle_params)

		if @motorcycle.save
			redirect_to motorcycles_path
		else
			render :new
		end
	end

	def destroy
		@motorcycle = Motorcycle.find(params[:id])
		@motorcycle.destroy
		redirect_to motorcycles_path
	end

	def edit
		@motorcycle = Motorcycle.find(params[:id])
	end

	def update

		@motorcycle = Motorcycle.find(params[:id])

		if @motorcycle.update_attributes(motorcycle_params)
			redirect_to motorcycles_path
		else 
			render "edit"
		end
	end
	
	private

	def motorcycle_params
		params.require(:motorcycle).permit(:name, :brand, :speed)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/views/bikes/edit.html.erb
<h1>Edit this bike!</h1>

<%= form_for @bike do |b| %>
	Name: <%= b.text_field :name %>
	Brand: <%= b.text_field :brand %>
	Speed: <%= b.text_field :speed %>
	<%= b.submit "Submit these changes!" %>
<% end %> </br>

<% link_to "Back to the list", bikes_path %>

app/views/bikes/index.html.erb
<div class="pure-menu pure-menu-open pure-menu-horizontal center-links">
    <ul>
        <li><a href="#">Home</a></li>
        <li class="pure-menu-selected"><a href="#">About</a></li>
        <li><a href="#">Our Company</a></li>
        <li><a href="#">Bike Routes</a></li>
        <li><a href=""><%= link_to "Motorcycles", motorcycles_path %></a></li>
    </ul>
</div>

<header>
	<h1>Carbon Fiber Bikes</h1>
</header>


<div id="container">
	<div id="right-div">
		<!-- <p>hello there</p> -->
		<!-- <img src="http://p1.pichost.me/640/20/1431682.jpg"> -->
		<img src="http://www.fuelyourcreativity.com/files/puegot-concept-bicycle1-600x352.jpg">
	</div>


	<div id="left-div">
		<ul>
		<% @bikes.each do |b| %>
		<li><%= b.name %> | <%= b.brand %> | <button><%= link_to "View", bike_path(b) %></button></li></br>
		
		<% end %>
		</ul>

		<button><span><%= link_to "Add a new bike", new_bike_path %></span></button>
	</div>

	
	
</div>

<footer> <p><strong>Actually</strong> backed by Dr. Dre and Snoop Dogg</p></footer>

app/views/bikes/new.html.erb
<h1>Add a new bike!</h1>

<%= form_for @bike do |b| %>
	<%= b.label :name %>
	<%= b.text_field :name %>

	<%= b.label :brand %>
	<%= b.text_field :brand %>

	<%= b.label :speed %>
	<%= b.text_field :speed %>

	<%= b.submit "Add bike" %>

<% end %>

<%= link_to "Back to the list", bikes_path %>

app/views/bikes/show.html.erb
<h1><%= @bike.name %></h1>

<p> This bike is a <%= @bike.brand %>. It's top speed is <%= @bike.speed %>. </p>

<button><%= link_to "Edit this bike", edit_bike_path %></button>

<button><%= link_to "Delete this bike", :bike, method: :delete, data: { confirm: "Are you sure you want to delete this bike? It's pretty bitchin!"} %></button> </br>


<button><%= link_to "Back to bikes", bikes_path %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bikeshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/motorcycles/edit.html.erb
<h1>Edit this Motorcycle!</h1>

<%= form_for @motorcycle do |f| %>
	Name: <%= f.text_field :name %>
	Brand: <%= f.text_field :brand %>
	Speed: <%= f.text_field :speed %>
	

	<button><%= f.submit "Submit these changes to the motorcycle!" %></button>

<% end %><br>



<button><%= link_to "Back to the list!", motorcycles_path %></button>

app/views/motorcycles/index.html.erb
<div class="pure-menu pure-menu-open pure-menu-horizontal center-links">
    <ul>
        <li><a href="#"><%= link_to "Home", bikes_path %></a></li>
        <li class="pure-menu-selected"><a href="#">About</a></li>
        <li><a href="#">Our Company</a></li>
        <li><a href="#">Bike Routes</a></li>
        <li><a href="#">Our Tech</a></li>
    </ul>
</div>

<header>
	<h1>Awesome Motorcycles</h1>
</header>


<div id="container">
	<div id="right-div">
		<!-- <p>hello there</p> -->
		<!-- <img src="http://p1.pichost.me/640/20/1431682.jpg"> -->
		<!-- <img id="motorcycle" src="http://pictures.topspeed.com/IMG/crop/201210/2013-star-motorcycle-raid-19_800x0w.jpg"> -->
		<img id="motorcycle" src="http://www.motorcycleshdwallpaper.com/wp-content/uploads/2012/10/Vehicles-motorcycles-ducati-gt-1000-free-backgrounds.jpg">
	</div>


	<div id="left-div">
		<ul>
		<% @motorcycles.each do |b| %>
		<li><%= b.name %> | <%= b.brand %> | <button><%= link_to "View", motorcycle_path(b) %></button></li></br>
		
		<% end %>
		</ul>

		<button><span><%= link_to "Add a new motorcycle", new_motorcycle_path %></span></button>
	</div>

	
	
</div>

app/views/motorcycles/new.html.erb
<h1>Add a new Motorcycle!</h1>

<%= form_for @motorcycle do |b| %>
	<%= b.label :name %>
	<%= b.text_field :name %>

	<%= b.label :brand %>
	<%= b.text_field :brand %>

	<%= b.label :speed %>
	<%= b.text_field :speed %>

	<%= b.submit "Add motorcycle" %>

<% end %>

<button><%= link_to "Back to the list", motorcycles_path %></button>

app/views/motorcycles/show.html.erb
<h1><%= @motorcycle.name %></h1>

<p> This motorcycle is a <%= @motorcycle.brand %>. It's top speed is <%= @motorcycle.speed %>. </p>

<button><%= link_to "Back to motorcycle", motorcycles_path %></button>
<button><%= link_to "Edit this motorcycle", edit_motorcycle_path %></button></br>

<button><%= link_to "Delete this motorcycle", :motorcycle, method: :delete, data: { confirm: "Are you sure you want to delete this motorcycle? It's pretty bitchin!"} %></button> 